//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace CST465_AC_Lab_2 {
    
    
    public partial class Assignment4Test {
        
        /// <summary>
        /// form1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        
        /// <summary>
        /// uxTFQuestionControl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CST465_AC_Lab_2.TrueFalseQuestion uxTFQuestionControl;
        
        /// <summary>
        /// uxMultQuestionControl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CST465_AC_Lab_2.MultipleChoiceQuestion uxMultQuestionControl;
        
        /// <summary>
        /// uxEssayQuestionControl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CST465_AC_Lab_2.EssayQuestion uxEssayQuestionControl;
        
        /// <summary>
        /// uxShortTextQuestionControl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CST465_AC_Lab_2.ShortTextQuestion uxShortTextQuestionControl;
    }
}
